/* eslint-disable */
// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Thin command to set file mtime — plugin-fs does not support setting mtime,
 * so this remains a Rust command used by writeNote and sync.
 */
async fsSetMtime(path: string, mtimeMs: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fs_set_mtime", { path, mtimeMs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fsListNotesWithMeta() : Promise<Result<NoteFileMeta[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fs_list_notes_with_meta") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fsWriteNoteAtomic(id: string, content: string, modifiedAtMs: number | null) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fs_write_note_atomic", { id, content, modifiedAtMs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fsSaveImage(sourcePath: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fs_save_image", { sourcePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read an image from the native clipboard and save as PNG.
 * Used on Linux/Wayland where WebKitGTK gives empty clipboardData to JS.
 */
async fsPasteClipboardImage() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fs_paste_clipboard_image") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fsStartWatcher() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fs_start_watcher") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fsListFolders() : Promise<Result<FolderEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fs_list_folders") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fsCreateFolder(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fs_create_folder", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fsRenameFolder(from: string, to: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fs_rename_folder", { from, to }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fsDeleteFolder(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fs_delete_folder", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fsDeleteNoteToTrash(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fs_delete_note_to_trash", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fsMoveNote(fromId: string, toId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fs_move_note", { fromId, toId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async notesDirOverrideLoad() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("notes_dir_override_load") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async notesDirOverrideSave(dir: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("notes_dir_override_save", { dir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resolves the default notes root, honoring the FUTO_NOTES_DATA_DIR env var
 * used to isolate per-worktree dev and cross-platform test runs. The webview
 * cannot read process env, so the TypeScript path layer delegates here.
 */
async resolveDefaultNotesRoot() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_default_notes_root") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async coreApplySyncDeltaV2(input: V2SyncApplyInput) : Promise<Result<V2SyncApplyOutput, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("core_apply_sync_delta_v2", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async e2eeConnect(input: E2eeConnectInput) : Promise<Result<E2eeConnectOutput, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("e2ee_connect", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async e2eeResume(input: E2eeResumeInput) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("e2ee_resume", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async e2eeDisconnect() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("e2ee_disconnect") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async e2eeStatus() : Promise<Result<E2eeStatusOutput, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("e2ee_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async e2eeSyncRun() : Promise<Result<SyncSummary, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("e2ee_sync_run") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async e2eeStartLive() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("e2ee_start_live") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async e2eeStopLive() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("e2ee_stop_live") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Signal that a local note changed (the write-once auto-push input). The TS
 * save path calls this; the live loop debounces and pushes the edit to peers.
 * No-op when no live task is running (disconnected) — so this is safe to call
 * unconditionally after every save. Replaces the desktop's
 * `notifySavedV2 → performSync('local-save')` path with a single Rust-side
 * debounce shared with native.
 */
async e2eeNoteChanged() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("e2ee_note_changed") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async showSoftKeyboard() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_soft_keyboard") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hapticImpact() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("haptic_impact") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Synchronously download the model + tokenizer if missing, load an
 * Embedder, embed `text`, and return timing + first-8 dims. Blocks the
 * caller — that's fine for a dev-only smoke test.
 */
async inferenceTestEmbed(text: string) : Promise<Result<InferenceTestResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("inference_test_embed", { text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async rulesSanitizeTitle(title: string) : Promise<string> {
    return await TAURI_INVOKE("rules_sanitize_title", { title });
},
/**
 * Returns the ordered list of issue-kind strings (e.g. `["forbidden_chars"]`).
 */
async rulesValidateTitle(title: string) : Promise<string[]> {
    return await TAURI_INVOKE("rules_validate_title", { title });
},
async rulesIsValidTitle(title: string) : Promise<boolean> {
    return await TAURI_INVOKE("rules_is_valid_title", { title });
},
async rulesMakeId(folder: string, title: string) : Promise<string> {
    return await TAURI_INVOKE("rules_make_id", { folder, title });
},
async rulesSplitId(id: string) : Promise<RuleNoteIdParts> {
    return await TAURI_INVOKE("rules_split_id", { id });
},
async rulesValidateFolderPath(path: string) : Promise<string[]> {
    return await TAURI_INVOKE("rules_validate_folder_path", { path });
},
async rulesIsValidFolderPath(path: string) : Promise<boolean> {
    return await TAURI_INVOKE("rules_is_valid_folder_path", { path });
},
async rulesPathDepth(path: string) : Promise<number> {
    return await TAURI_INVOKE("rules_path_depth", { path });
},
/**
 * Canonical `#tags` (WITH the leading `#`) excluding code regions.
 */
async rulesExtractTags(content: string) : Promise<string[]> {
    return await TAURI_INVOKE("rules_extract_tags", { content });
},
async rulesExtractHeaderTagBlock(content: string) : Promise<RuleHeaderTagBlock> {
    return await TAURI_INVOKE("rules_extract_header_tag_block", { content });
},
async rulesIsImageFilename(filename: string) : Promise<boolean> {
    return await TAURI_INVOKE("rules_is_image_filename", { filename });
},
/**
 * ~100-char list preview (CR/LF/TAB → single spaces, trimmed). The single
 * source of truth for the preview rule — the TS `makePreview()` is kept
 * bit-for-bit identical to this for the synchronous hot path. Routed through
 * `rules.rs` (not `notes.rs`) because it is a pure deterministic rule, not a
 * CRUD command.
 */
async rulesMakePreview(content: string) : Promise<string> {
    return await TAURI_INVOKE("rules_make_preview", { content });
},
/**
 * Canonical wikilink targets (`[[...]]` excluding code regions). Exposed for
 * non-hot-path / cross-platform use; the per-keystroke TS copy stays in
 * `@futo-notes/editor`.
 */
async rulesExtractWikilinks(content: string) : Promise<string[]> {
    return await TAURI_INVOKE("rules_extract_wikilinks", { content });
},
/**
 * Scan all notes, sorted by mtime descending. One IPC returns the whole
 * vault's metadata (coarse by design — mirrors FFI `scan_notes`).
 */
async notesScan() : Promise<Result<NoteMeta[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("notes_scan") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * All folder paths (note ancestors + empty dirs), sorted.
 */
async notesScanFolders() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("notes_scan_folders") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read a note's content (`""` if missing).
 */
async notesRead(id: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("notes_read", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Whether a note exists on disk.
 */
async notesExists(id: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("notes_exists", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async notesWrite(id: string, content: string, modifiedAtMs: number | null) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("notes_write", { id, content, modifiedAtMs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async notesCreate(title: string, folder: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("notes_create", { title, folder }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async notesDelete(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("notes_delete", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async notesRename(oldId: string, newId: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("notes_rename", { oldId, newId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async notesMove(id: string, folder: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("notes_move", { id, folder }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a folder (+ intermediates). Returns the sanitized path (or `""`).
 */
async notesCreateFolder(path: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("notes_create_folder", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async notesDeleteToTrash(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("notes_delete_to_trash", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async notesRenameFolder(from: string, to: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("notes_rename_folder", { from, to }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async notesDeleteFolder(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("notes_delete_folder", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run a hybrid query. BM25-only until the SPLADE backfill is ready, then
 * BM25 ⊕ SPLADE fused via RRF.
 */
async searchQuery(query: string, limit: number | null) : Promise<Result<SearchHit[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_query", { query, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Current indexing status: keyword readiness + SPLADE backfill progress.
 */
async searchStatus() : Promise<Result<SearchStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Force a full corpus rescan (clears cached SPLADE encode progress and
 * re-runs reconcile + backfill). Exposed for the Settings "rebuild index"
 * affordance and tests — NOT for routine edits (use [`search_notify`]).
 */
async searchRebuild() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_rebuild") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Incremental index update for a single note, driven by the frontend's
 * existing `fs:change` subscription. `kind` is one of `"add"`, `"change"`,
 * `"unlink"`, or `"rename"`; `rel_path` is the note's path relative to the
 * vault root, and `from` carries the old path for renames. These are
 * debounced + mtime-aware inside the engine, so this is cheap to call on every
 * edit (unlike `search_rebuild`, which force-re-encodes the whole corpus).
 */
async searchNotify(kind: string, relPath: string, from: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_notify", { kind, relPath, from }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type E2eeConnectInput = { serverUrl: string; password: string }
export type E2eeConnectOutput = { userId: string; collectionId: string; 
/**
 * Bearer token; JS persists this so `e2ee_resume` can skip login on
 * app restart. If it expires, `e2ee_resume` will surface the 401 and
 * JS should fall back to `e2ee_connect`.
 */
token: string; 
/**
 * Whether the server identified itself as `password` or `dev` mode.
 * JS uses this to gate the UI affordances around the stored password.
 */
authMode: string }
export type E2eeResumeInput = { serverUrl: string; token: string; userId: string; collectionId: string; password: string }
export type E2eeStatusOutput = { connected: boolean; serverUrl?: string | null; userId?: string | null; collectionId?: string | null; maxVersion: number; objectCount: number; migratedLegacy: boolean }
export type FolderEntry = { path: string }
export type InferenceTestResult = { loadMs: number; embedMs: number; dims: number; 
/**
 * First 8 components of the output vector. Just enough to eyeball
 * that the output isn't all zeros / NaN without flooding the log.
 */
firstEight: number[]; modelPath: string }
export type KeywordStatus = { ready: boolean }
/**
 * One-shot recursive readdir+stat for `.md` files, sorted by mtime desc.
 * `name` is the relative path from the notes root (e.g. `Specs/foo.md`)
 * using forward slashes on every platform.
 */
export type NoteFileMeta = { name: string; mtimeMs: number; sizeBytes: number }
/**
 * One note's list-level metadata. Mirrors the FFI `NoteMetadata` but in
 * camelCase + the existing TS `NotePreview` field set, so `notesCache` feeds
 * with a tiny shim and zero remapping. `modifiedMs` maps to
 * `NotePreview.modificationTime`; `tags` are canonical lowercase, NO leading
 * `#`.
 */
export type NoteMeta = { id: string; title: string; folder: string; modifiedMs: number; preview: string; tags: string[] }
export type RenamePair = { fromId: string; toId: string }
/**
 * Header tag block result: canonical `#tags` + the byte offset where the
 * block ends.
 */
export type RuleHeaderTagBlock = { tags: string[]; endOffset: number }
/**
 * `(folder, title)` split of a note id.
 */
export type RuleNoteIdParts = { folder: string; title: string }
/**
 * A ranked search result. `source` is `"bm25"` until SPLADE is ready, then
 * `"hybrid"`.
 */
export type SearchHit = { noteId: string; score: number; 
/**
 * "bm25" | "hybrid"
 */
source: string }
export type SearchStatus = { keyword: KeywordStatus; splade: SpladeStatus }
export type SpladeStatus = { ready: boolean; indexed: number; total: number; 
/**
 * First-launch compile of the CoreML MLProgram blocks `SpladeDocEncoder::load`
 * for ~40s on Apple Silicon. We surface that as a distinct UI state so the
 * indicator doesn't look frozen at "0 / N".
 */
compiling: boolean; 
/**
 * One of: "model_file_missing", "encoder_load_failed",
 * "armv7_unsupported", "indexer_crashed", or None.
 */
fallbackReason: string | null }
/**
 * Wire `SyncSummary` returned by `e2ee_sync_run` and emitted on
 * `sync:live-synced`. Identical to the pre-relocation shape so the JS
 * `SyncSummary` type (in `bindings.ts`) is unchanged. The crate's rich
 * `SyncSummary` carries ids already stripped of `.md`; this just copies
 * the count + id-list + rename fields out of it.
 */
export type SyncSummary = { uploaded: number; downloaded: number; deleted: number; conflicts: number; updatedIds: string[]; deletedIds: string[]; peerUpdatedIds: string[]; peerDeletedIds: string[]; renamed: RenamePair[] }
export type V2IncomingConflict = { filename: string; content: string }
export type V2IncomingUpdate = { filename: string; content: string; hash: string; modified_at: number }
export type V2SyncApplyInput = { update: V2IncomingUpdate[]; delete: string[]; conflicts: V2IncomingConflict[]; timestamps?: Partial<{ [key in string]: number }> }
export type V2SyncApplyOutput = { updatedFilenames: string[]; deletedFilenames: string[]; conflictFilenames: string[]; elapsedMs: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
