services:
  server:
    container_name: stonefruit
    image: gitlab.futo.org:5050/stonefruit/stonefruit/server:latest
    ports:
      - "3005:3005"
    volumes:
      - ${STONEFRUIT_DATA_PATH:-./stonefruit-data}:/app/apps/server/data
    environment:
      - PORT=3005
      - DATABASE_PATH=./data/stonefruit.db
      - NOTES_PATH=./data/notes
    restart: unless-stopped
