services:
  server:
    build:
      context: ../..
      dockerfile: crates/stonefruit-server/Dockerfile
    ports:
      - "${PORT:-3005}:${PORT:-3005}"
    volumes:
      - ${STONEFRUIT_DATA_PATH:-./data}:/app/data
    environment:
      - PORT=${PORT:-3005}
      - RUST_LOG=${RUST_LOG:-stonefruit_server=info}
