// GENERATED FILE — DO NOT EDIT.
// Source: apps/tauri/src-tauri/src/sync/frontend_contract.rs.

// This file has been generated by Specta. Do not edit this file manually.
export type E2eeConnectInput = {
	serverUrl: string,
	password: string,
};

export type E2eeConnectOutput = {
	userId: string,
	collectionId: string,
	token: string,
	authMode: string,
};

export type E2eeResumeInput = {
	serverUrl: string,
	token: string,
	userId: string,
	collectionId: string,
	password: string,
};

export type E2eeStatusOutput = {
	connected: boolean,
	serverUrl?: string | null,
	userId?: string | null,
	collectionId?: string | null,
	maxVersion: number,
	objectCount: number,
};

export type KeepDraftReasonOutput = "peerDeleted" | "diverged" | "converged";

/**
 *  The engine's verdict on the open note, tagged the same way a flush
 *  disposition is so the frontend renders both through one shape.
 */
export type OpenNoteDispositionOutput = { kind: "leave" } | { kind: "adopt"; content: string } | { kind: "deferAdopt" } | { kind: "followRename"; toId: string } | { kind: "keepDraft"; base: string; reason: KeepDraftReasonOutput } | { kind: "close" };

/**
 *  The facts the frontend gathers before asking the engine what happens to the
 *  open note. Field-for-field the engine's `OpenNoteFacts`; see that type for
 *  what each one means.
 */
export type OpenNoteFactsInput = {
	base: string,
	draft: string,
	disk: string | null,
	renamedTo: string | null,
	editorFocused: boolean,
	editedDuringCycle: boolean,
	adoptPreservesCaret: boolean,
};

export type RenamePair = {
	fromId: string,
	toId: string,
};

export type SyncFailure = {
	filename: string,
	kind: string,
	statusCode: number | null,
};

export type SyncSummary = {
	uploaded: number,
	downloaded: number,
	deleted: number,
	conflicts: number,
	/**
	 *  Count of note files this cycle wrote to the local tree (F2). Desktop
	 *  already reloads on `updated_ids`, so it doesn't gate on this; it is
	 *  carried for wire parity with the native FFI summary.
	 */
	localWritesApplied: number,
	failures: SyncFailure[],
	failureMessage: string | null,
	updatedIds: string[],
	deletedIds: string[],
	peerUpdatedIds: string[],
	peerDeletedIds: string[],
	renamed: RenamePair[],
};
