// GENERATED FILE — DO NOT EDIT.
// Source: apps/tauri/src-tauri/src/sync/frontend_contract.rs.

// This file has been generated by Specta. Do not edit this file manually.
// What the account card reads. `entitled` is the only field to act on.
export type BillingStatusOutput = {
	entitled: boolean,
	state: string,
	graceUntil: string | null,
	storageQuotaBytes: number,
	blobMaxBytes: number,
	bytesUsed: number,
};

export type CheckoutOutput = 
// Open this in the browser, then await entitlement.
{ kind: "open"; url: string } | 
// Nothing to buy; this account may already write.
{ kind: "alreadyEntitled"; status: BillingStatusOutput };

export type E2eeConnectInput = {
	serverUrl: string,
	password: string,
};

export type E2eeConnectOutput = {
	userId: string,
	collectionId: string,
	token: string,
	authMode: string,
};

export type E2eeResumeInput = {
	serverUrl: string,
	token: string,
	userId: string,
	collectionId: string,
	password: string,
};

export type E2eeStatusOutput = {
	connected: boolean,
	serverUrl?: string | null,
	userId?: string | null,
	collectionId?: string | null,
	maxVersion: number,
	objectCount: number,
};

export type EntitlementOutcomeOutput = { kind: "entitled"; status: BillingStatusOutput } | { kind: "cancelled" } | 
// The wait ran out; `status` is the last reading.
{ kind: "gaveUp"; status: BillingStatusOutput };

/**
 *  Why a hosted step failed, as a variant rather than a sentence: each one is
 *  a different thing for a person to do about it, and `signInAgain` in
 *  particular must never be rendered as a broken vault. The sentence-carrying
 *  field is `reason`, matching the name the native contract is forced into (a
 *  `message` on a UniFFI error collides with `Throwable.message` in Kotlin), so
 *  all three shells read one vocabulary.
 */
export type HostedErrorOutput = 
// The session is gone. Sign in again; sync state is untouched.
{ kind: "signInAgain" } | { kind: "notSignedIn" } | 
// This server does not offer hosted sync.
{ kind: "notHosted"; reason: string } | { kind: "rateLimited"; retryAfterSeconds: number } | { kind: "server"; reason: string } | { kind: "network"; reason: string } | 
// Creating a vault is an entitlement-gated write: subscribe first.
{ kind: "notEntitled" } | 
// This account already has a vault. Unlock it rather than replacing it.
{ kind: "vaultAlreadyExists" } | { kind: "noVault" } | { kind: "vaultPasswordTooShort"; minimum: number } | 
// The one failure a person fixes by typing again.
{ kind: "wrongVaultPassword" } | 
// Not a recovery key at all; caught on the device.
{ kind: "recoveryKeyFormat" } | 
/**
 *  A mistyped or transposed character, caught by the check character
 *  before anything is sent.
 */
{ kind: "recoveryKeyTypo" } | { kind: "wrongRecoveryKey" } | { kind: "noRecoveryKey" } | 
// The OS secret store refused; nothing was kept.
{ kind: "secretStore"; reason: string } | { kind: "crypto"; reason: string };

export type HostedSessionOutput = {
	userId: string,
	email: string,
	name: string,
	token: string,
};

export type KeepDraftReasonOutput = "peerDeleted" | "diverged" | "converged";

/**
 *  The engine's verdict on the open note, tagged the same way a flush
 *  disposition is so the frontend renders both through one shape.
 */
export type OpenNoteDispositionOutput = { kind: "leave" } | { kind: "adopt"; content: string } | { kind: "deferAdopt" } | { kind: "followRename"; toId: string } | { kind: "keepDraft"; base: string; reason: KeepDraftReasonOutput } | { kind: "close" };

/**
 *  The editor facts supplied by the frontend. The adapter gathers the
 *  authoritative disk value before asking the engine for a verdict.
 */
export type OpenNoteRequestInput = {
	id: string,
	base: string,
	draft: string,
	renamedTo: string | null,
	editorFocused: boolean,
	editedDuringCycle: boolean,
};

export type RenamePair = {
	fromId: string,
	toId: string,
};

/**
 *  Which screen the hosted wizard is on, derived from server facts and this
 *  device's secret store — never from a stored position.
 */
export type SetupStepOutput = { kind: "signIn" } | { kind: "subscribe" } | { kind: "createVault" } | { kind: "unlock" } | { kind: "ready" };

// How the app should log in to a server, read from its capability document.
export type SignInFlowOutput = { kind: "hosted"; 
/**
 *  Whether this deployment sells subscriptions, and therefore whether
 *  the wizard has a subscribe step.
 */
sellsSubscriptions: boolean } | { kind: "password" } | { kind: "dev" };

/**
 *  A minted Login Hand-off. `url` goes to the system browser; `handoff` comes
 *  back to `e2ee_hosted_await_sign_in` unchanged.
 */
export type SignInHandoffOutput = {
	url: string,
	ticket: string,
};

export type SignInOutcomeOutput = { kind: "signedIn"; session: HostedSessionOutput } | 
// The browser window was abandoned. No error and no half state.
{ kind: "cancelled" } | 
// Mint a new hand-off and open the URL again.
{ kind: "expired" };

export type SyncFailure = {
	filename: string,
	kind: string,
	statusCode: number | null,
};

export type SyncSummary = {
	uploaded: number,
	downloaded: number,
	deleted: number,
	conflicts: number,
	/**
	 *  Count of note files this cycle wrote to the local tree (F2). Desktop
	 *  already reloads on `updated_ids`, so it doesn't gate on this; it is
	 *  carried for wire parity with the native FFI summary.
	 */
	localWritesApplied: number,
	failures: SyncFailure[],
	failureMessage: string | null,
	updatedIds: string[],
	deletedIds: string[],
	peerUpdatedIds: string[],
	peerDeletedIds: string[],
	renamed: RenamePair[],
};
