// GENERATED FILE — DO NOT EDIT.
// Source: apps/tauri/src-tauri/src/sync/frontend_contract.rs.

// This file has been generated by Specta. Do not edit this file manually.
export type E2eeConnectInput = {
	serverUrl: string,
	password: string,
};

export type E2eeConnectOutput = {
	userId: string,
	collectionId: string,
	token: string,
	authMode: string,
};

export type E2eeResumeInput = {
	serverUrl: string,
	token: string,
	userId: string,
	collectionId: string,
	password: string,
};

export type E2eeStatusOutput = {
	connected: boolean,
	serverUrl?: string | null,
	userId?: string | null,
	collectionId?: string | null,
	maxVersion: number,
	objectCount: number,
};

export type RenamePair = {
	fromId: string,
	toId: string,
};

export type SyncFailure = {
	filename: string,
	kind: string,
	statusCode: number | null,
};

export type SyncSummary = {
	uploaded: number,
	downloaded: number,
	deleted: number,
	conflicts: number,
	/**
	 *  Count of note files this cycle wrote to the local tree (F2). Desktop
	 *  already reloads on `updated_ids`, so it doesn't gate on this; it is
	 *  carried for wire parity with the native FFI summary.
	 */
	localWritesApplied: number,
	failures: SyncFailure[],
	failureMessage: string | null,
	updatedIds: string[],
	deletedIds: string[],
	peerUpdatedIds: string[],
	peerDeletedIds: string[],
	renamed: RenamePair[],
};
