import fs from 'node:fs';
import path from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { getDb } from '../../src/db/index.js';
import { upsertNote, getNote } from '../../src/db/notes.js';
import { contentHash } from '../../src/sync/hash.js';
import { __setTestLlmResponder } from '../../src/plugins/llm.js';
import { authReq, createTestEnv, setupAndLogin, type TestEnv } from '../helpers/setup.js';

function createSSEReader(res: Response) {
  const reader = res.body!.getReader();
  const decoder = new TextDecoder();
  let buffer = '';

  return {
    async readUntil(predicate: (buf: string) => boolean, timeoutMs = 2000): Promise<string> {
      if (predicate(buffer)) return buffer;

      const timeout = new Promise<never>((_, reject) =>
        setTimeout(() => reject(new Error('SSE read timed out')), timeoutMs),
      );

      const read = async (): Promise<string> => {
        while (true) {
          const { value, done } = await reader.read();
          if (done) break;
          buffer += decoder.decode(value, { stream: true });
          if (predicate(buffer)) return buffer;
        }
        return buffer;
      };

      return Promise.race([read(), timeout]);
    },

    cancel() {
      reader.cancel();
    },

    get contents() {
      return buffer;
    },
  };
}

async function waitForRunDetail(
  app: TestEnv['app'],
  token: string,
  runId: string,
): Promise<{ run: { status: string }; items: Array<Record<string, unknown>> }> {
  for (let i = 0; i < 40; i++) {
    const res = await authReq(app, 'GET', `/plugins/runs/${runId}`, token);
    if (res.status === 200) {
      const data = await res.json() as { run: { status: string }; items: Array<Record<string, unknown>> };
      if (data.run.status !== 'running') {
        return data;
      }
    }
    await new Promise((resolve) => setTimeout(resolve, 25));
  }
  throw new Error(`Timed out waiting for run ${runId}`);
}

function seedNote(env: TestEnv, uuid: string, filename: string, content: string, modifiedAt = Date.now()): void {
  fs.mkdirSync(env.notesDir, { recursive: true });
  fs.writeFileSync(path.join(env.notesDir, filename), content, 'utf8');
  upsertNote(getDb(), uuid, filename, contentHash(content), modifiedAt);
}

async function createSseTicket(app: TestEnv['app'], token: string): Promise<string> {
  const res = await app.request('/events/session', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
    },
  });
  expect(res.status).toBe(200);
  const data = await res.json() as { ticket: string };
  return data.ticket;
}

function buildLocalPluginSource(pluginId: string, title: string, description = 'Local automation for tests.'): string {
  return `export default {
  id: '${pluginId}',
  name: '${title}',
  description: '${description}',
  defaultEnabled: false,
  defaultSchedule: { kind: 'manual', time: null, day: null },
  defaultAutoApply: false,
  configSchema: [
    { key: 'targetTitle', label: 'Target title', type: 'string', default: 'local title' },
  ],
  async run(context) {
    const notes = await context.sdk.findNotes({ filenameGlob: 'Untitled*.md', limit: 1, sort: 'modified_desc' });
    if (notes.length === 0) {
      return { notesScanned: 0, proposalsCreated: 0, notesSkipped: 0 };
    }

    const note = notes[0];
    const targetTitle = String(context.config.targetTitle || 'local title');
    await context.sdk.proposeChange({
      entityType: 'note',
      entityId: note.uuid,
      changeType: 'rename_note',
      before: { title: note.title, filename: note.filename },
      after: { newTitle: targetTitle, rewriteExactWikiLinks: true },
      preview: { oldTitle: note.title, proposedTitle: targetTitle, noteUuid: note.uuid },
      reason: 'Generated by local plugin test',
    });

    await context.sdk.log('info', 'Local plugin proposed rename', { noteUuid: note.uuid, targetTitle });
    return { notesScanned: 1, proposalsCreated: 1, notesSkipped: 0 };
  },
};
`;
}

describe('Plugins', () => {
  let env: TestEnv;

  beforeEach(() => {
    env = createTestEnv();
    __setTestLlmResponder(null);
  });

  afterEach(() => {
    __setTestLlmResponder(null);
    env.cleanup();
  });

  it('lists built-in automation status', async () => {
    const token = await setupAndLogin(env.app);
    const res = await authReq(env.app, 'GET', '/plugins/status', token);
    expect(res.status).toBe(200);

    const data = await res.json() as {
      plugins: Array<{ id: string; auto_apply: boolean; config_schema: Array<{ key: string }> }>;
      scheduler: { phase: string };
    };

    expect(data.scheduler.phase).toBe('idle');
    expect(data.plugins).toHaveLength(1);
    expect(data.plugins[0].id).toBe('untitled-no-more');
    expect(data.plugins[0].auto_apply).toBe(false);
    expect(data.plugins[0].config_schema).toEqual([]);
  });

  it('creates preview suggestions and applies approved rename with wikilink rewrite', async () => {
    const token = await setupAndLogin(env.app);
    __setTestLlmResponder(() => 'meeting notes');

    const oldMtime = Date.now() - (10 * 60 * 1000);
    seedNote(env, 'note-1', 'Untitled.md', 'Agenda for the team sync and follow-up action items.', oldMtime);
    seedNote(env, 'note-2', 'Reference.md', 'See [[Untitled]] before next week.', oldMtime);

    const runRes = await authReq(env.app, 'POST', '/plugins/untitled-no-more/run', token);
    expect(runRes.status).toBe(202);
    const { run_id } = await runRes.json() as { run_id: string };

    const preview = await waitForRunDetail(env.app, token, run_id);
    expect(preview.run.status).toBe('awaiting_approval');
    expect(preview.items).toHaveLength(1);
    expect(preview.items[0].status).toBe('suggested');
    expect(preview.items[0].preview).toMatchObject({
      oldTitle: 'Untitled',
      proposedTitle: 'meeting notes',
      rewriteExactWikiLinks: true,
    });

    const itemId = Number(preview.items[0].id);
    const approveRes = await authReq(env.app, 'POST', `/plugins/runs/${run_id}/items/${itemId}/approve`, token);
    expect(approveRes.status).toBe(200);

    const applyRes = await authReq(env.app, 'POST', `/plugins/runs/${run_id}/apply-approved`, token);
    expect(applyRes.status).toBe(200);

    const applied = await waitForRunDetail(env.app, token, run_id);
    expect(applied.run.status).toBe('succeeded');
    expect(applied.items[0].status).toBe('applied');

    const renamed = getNote(getDb(), 'note-1');
    expect(renamed?.filename).toBe('meeting notes.md');
    const referenceContent = fs.readFileSync(path.join(env.notesDir, 'Reference.md'), 'utf8');
    expect(referenceContent).toContain('[[meeting notes]]');
    expect(referenceContent).not.toContain('[[Untitled]]');
  });

  it('supports auto-apply runs via plugin config', async () => {
    const token = await setupAndLogin(env.app);
    __setTestLlmResponder(() => 'trip planning');

    const configRes = await authReq(env.app, 'POST', '/plugins/untitled-no-more/config', token, {
      auto_apply: true,
      schedule_kind: 'manual',
      config: {
        maxContentChars: 1500,
      },
    });
    expect(configRes.status).toBe(200);

    const oldMtime = Date.now() - (10 * 60 * 1000);
    seedNote(env, 'note-3', 'Untitled (2).md', 'Reservations, packing list, and places to visit.', oldMtime);

    const runRes = await authReq(env.app, 'POST', '/plugins/untitled-no-more/run', token);
    expect(runRes.status).toBe(202);
    const { run_id } = await runRes.json() as { run_id: string };

    const detail = await waitForRunDetail(env.app, token, run_id);
    expect(detail.run.status).toBe('succeeded');
    expect(detail.items[0].status).toBe('applied');

    const renamed = getNote(getDb(), 'note-3');
    expect(renamed?.filename).toBe('trip planning.md');
  });

  it('broadcasts sync_available after an auto-applied rename', async () => {
    const token = await setupAndLogin(env.app);
    __setTestLlmResponder(() => 'trip planning');

    const configRes = await authReq(env.app, 'POST', '/plugins/untitled-no-more/config', token, {
      auto_apply: true,
      schedule_kind: 'manual',
      config: {},
    });
    expect(configRes.status).toBe(200);

    const ticket = await createSseTicket(env.app, token);
    const sseRes = await env.app.request(`/events?ticket=${ticket}&clientId=observer`);
    expect(sseRes.status).toBe(200);
    const sse = createSSEReader(sseRes);

    try {
      await sse.readUntil((buf) => buf.includes('event: connected'));

      const oldMtime = Date.now() - (10 * 60 * 1000);
      seedNote(env, 'note-5', 'Untitled.md', 'Reservations, packing list, and places to visit.', oldMtime);

      const runRes = await authReq(env.app, 'POST', '/plugins/untitled-no-more/run', token);
      expect(runRes.status).toBe(202);
      const { run_id } = await runRes.json() as { run_id: string };

      await sse.readUntil((buf) => buf.includes('event: sync_available'));
      const detail = await waitForRunDetail(env.app, token, run_id);
      expect(detail.run.status).toBe('succeeded');
      expect(sse.contents).toContain('event: sync_available');
    } finally {
      sse.cancel();
    }
  });

  it('bumps sync version after an auto-applied rename', async () => {
    const token = await setupAndLogin(env.app);
    __setTestLlmResponder(() => 'trip planning');

    const beforeRes = await authReq(env.app, 'POST', '/sync/check', token, { version: 0 });
    expect(beforeRes.status).toBe(200);
    const before = await beforeRes.json() as { status: string; version: number };
    expect(before.status).toBe('up_to_date');
    expect(before.version).toBe(0);

    const configRes = await authReq(env.app, 'POST', '/plugins/untitled-no-more/config', token, {
      auto_apply: true,
      schedule_kind: 'manual',
      config: {},
    });
    expect(configRes.status).toBe(200);

    const oldMtime = Date.now() - (10 * 60 * 1000);
    seedNote(env, 'note-6', 'Untitled.md', 'Reservations, packing list, and places to visit.', oldMtime);

    const runRes = await authReq(env.app, 'POST', '/plugins/untitled-no-more/run', token);
    expect(runRes.status).toBe(202);
    const { run_id } = await runRes.json() as { run_id: string };

    const detail = await waitForRunDetail(env.app, token, run_id);
    expect(detail.run.status).toBe('succeeded');

    const afterRes = await authReq(env.app, 'POST', '/sync/check', token, { version: 0 });
    expect(afterRes.status).toBe(200);
    const after = await afterRes.json() as { status: string; version: number };
    expect(after.status).toBe('changes_available');
    expect(after.version).toBeGreaterThan(0);
  });

  it('retries once when the title model returns an empty response', async () => {
    const token = await setupAndLogin(env.app);
    let calls = 0;
    __setTestLlmResponder((input) => {
      calls += 1;
      expect(input.disableThinking).toBe(true);
      return calls === 1 ? '' : 'gettysburg address';
    });

    const oldMtime = Date.now() - (10 * 60 * 1000);
    seedNote(
      env,
      'note-4',
      'Untitled.md',
      'the gettysburg address was an important speech. abrham lincoln really cooked with that one. but it was an important speech because of the message.',
      oldMtime,
    );

    const runRes = await authReq(env.app, 'POST', '/plugins/untitled-no-more/run', token);
    expect(runRes.status).toBe(202);
    const { run_id } = await runRes.json() as { run_id: string };

    const preview = await waitForRunDetail(env.app, token, run_id);
    expect(calls).toBe(2);
    expect(preview.run.status).toBe('awaiting_approval');
    expect(preview.items[0].preview).toMatchObject({
      oldTitle: 'Untitled',
      proposedTitle: 'gettysburg address',
    });
  });

  it('creates, edits, runs, and deletes a local plugin while keeping run history', async () => {
    const token = await setupAndLogin(env.app);
    seedNote(env, 'local-note-1', 'Untitled.md', 'This note should be renamed by a local plugin.', Date.now() - 60_000);

    const createRes = await authReq(env.app, 'POST', '/plugins/local', token, {
      plugin_id: 'local-renamer',
      source: buildLocalPluginSource('local-renamer', 'Local Renamer'),
    });
    expect(createRes.status).toBe(201);

    const statusRes = await authReq(env.app, 'GET', '/plugins/status', token);
    expect(statusRes.status).toBe(200);
    const status = await statusRes.json() as {
      plugins: Array<{ id: string; source_kind: string; source_label: string; can_edit: boolean }>;
    };
    const localPlugin = status.plugins.find((plugin) => plugin.id === 'local-renamer');
    expect(localPlugin).toMatchObject({
      id: 'local-renamer',
      source_kind: 'local',
      source_label: 'Local',
      can_edit: true,
    });

    const sourceRes = await authReq(env.app, 'GET', '/plugins/local/local-renamer/source', token);
    expect(sourceRes.status).toBe(200);
    const sourceData = await sourceRes.json() as { source: string };
    expect(sourceData.source).toContain("name: 'Local Renamer'");

    const runRes = await authReq(env.app, 'POST', '/plugins/local-renamer/run', token);
    expect(runRes.status).toBe(202);
    const { run_id } = await runRes.json() as { run_id: string };

    const preview = await waitForRunDetail(env.app, token, run_id);
    expect(preview.run.status).toBe('awaiting_approval');
    expect(preview.items).toHaveLength(1);
    expect(preview.items[0].preview).toMatchObject({
      oldTitle: 'Untitled',
      proposedTitle: 'local title',
    });

    const updateRes = await authReq(env.app, 'PUT', '/plugins/local/local-renamer/source', token, {
      source: buildLocalPluginSource('local-renamer', 'Local Renamer v2', 'Updated local automation.'),
    });
    expect(updateRes.status).toBe(200);

    const updatedStatusRes = await authReq(env.app, 'GET', '/plugins/status', token);
    expect(updatedStatusRes.status).toBe(200);
    const updatedStatus = await updatedStatusRes.json() as {
      plugins: Array<{ id: string; name: string; description: string }>;
    };
    expect(updatedStatus.plugins.find((plugin) => plugin.id === 'local-renamer')).toMatchObject({
      id: 'local-renamer',
      name: 'Local Renamer v2',
      description: 'Updated local automation.',
    });

    const deleteRes = await authReq(env.app, 'DELETE', '/plugins/local/local-renamer', token);
    expect(deleteRes.status).toBe(200);

    const statusAfterDeleteRes = await authReq(env.app, 'GET', '/plugins/status', token);
    expect(statusAfterDeleteRes.status).toBe(200);
    const statusAfterDelete = await statusAfterDeleteRes.json() as {
      plugins: Array<{ id: string }>;
    };
    expect(statusAfterDelete.plugins.find((plugin) => plugin.id === 'local-renamer')).toBeUndefined();

    const runDetailAfterDeleteRes = await authReq(env.app, 'GET', `/plugins/runs/${run_id}`, token);
    expect(runDetailAfterDeleteRes.status).toBe(200);
    const runDetailAfterDelete = await runDetailAfterDeleteRes.json() as { run: { plugin_id: string } };
    expect(runDetailAfterDelete.run.plugin_id).toBe('local-renamer');
  });
});
