import fs from 'node:fs';
import path from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { getDb } from '../../src/db/index.js';
import { upsertNote, getNote } from '../../src/db/notes.js';
import { contentHash } from '../../src/sync/hash.js';
import { __setTestLlmResponder } from '../../src/plugins/llm.js';
import { authReq, createTestEnv, setupAndLogin, type TestEnv } from '../helpers/setup.js';

function createSSEReader(res: Response) {
  const reader = res.body!.getReader();
  const decoder = new TextDecoder();
  let buffer = '';

  return {
    async readUntil(predicate: (buf: string) => boolean, timeoutMs = 2000): Promise<string> {
      if (predicate(buffer)) return buffer;

      const timeout = new Promise<never>((_, reject) =>
        setTimeout(() => reject(new Error('SSE read timed out')), timeoutMs),
      );

      const read = async (): Promise<string> => {
        while (true) {
          const { value, done } = await reader.read();
          if (done) break;
          buffer += decoder.decode(value, { stream: true });
          if (predicate(buffer)) return buffer;
        }
        return buffer;
      };

      return Promise.race([read(), timeout]);
    },

    cancel() {
      reader.cancel();
    },

    get contents() {
      return buffer;
    },
  };
}

async function waitForRunDetail(
  app: TestEnv['app'],
  token: string,
  runId: string,
): Promise<{ run: { status: string }; items: Array<Record<string, unknown>> }> {
  for (let i = 0; i < 40; i++) {
    const res = await authReq(app, 'GET', `/plugins/runs/${runId}`, token);
    if (res.status === 200) {
      const data = await res.json() as { run: { status: string }; items: Array<Record<string, unknown>> };
      if (data.run.status !== 'running') {
        return data;
      }
    }
    await new Promise((resolve) => setTimeout(resolve, 25));
  }
  throw new Error(`Timed out waiting for run ${runId}`);
}

async function waitForRunAllBatch(
  app: TestEnv['app'],
  token: string,
  batchId: string,
): Promise<{
  batch_id: string;
  status: string;
  items: Array<{ plugin_id: string; status: string; error_message: string | null }>;
}> {
  for (let i = 0; i < 80; i++) {
    const res = await authReq(app, 'GET', '/plugins/status', token);
    if (res.status === 200) {
      const data = await res.json() as {
        run_all_batch?: {
          batch_id: string;
          status: string;
          items: Array<{ plugin_id: string; status: string; error_message: string | null }>;
        } | null;
      };
      if (data.run_all_batch && data.run_all_batch.batch_id === batchId && data.run_all_batch.status === 'completed') {
        return data.run_all_batch;
      }
    }
    await new Promise((resolve) => setTimeout(resolve, 25));
  }
  throw new Error(`Timed out waiting for batch ${batchId}`);
}

function seedNote(env: TestEnv, uuid: string, filename: string, content: string, modifiedAt = Date.now()): void {
  fs.mkdirSync(env.notesDir, { recursive: true });
  fs.writeFileSync(path.join(env.notesDir, filename), content, 'utf8');
  upsertNote(getDb(), uuid, filename, contentHash(content), modifiedAt);
}

async function createSseTicket(app: TestEnv['app'], token: string): Promise<string> {
  const res = await app.request('/events/session', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
    },
  });
  expect(res.status).toBe(200);
  const data = await res.json() as { ticket: string };
  return data.ticket;
}

function buildLocalPluginSource(pluginId: string, title: string, description = 'Local automation for tests.'): string {
  return `export default {
  id: '${pluginId}',
  name: '${title}',
  description: '${description}',
  defaultEnabled: false,
  defaultSchedule: { kind: 'manual', time: null, day: null },
  defaultAutoApply: true,
  configSchema: [
    { key: 'targetTitle', label: 'Target title', type: 'string', default: 'local title' },
  ],
  async run(context) {
    const notes = await context.sdk.findNotes({ filenameGlob: 'Untitled*.md', limit: 1, sort: 'modified_desc' });
    if (notes.length === 0) {
      return { notesScanned: 0, proposalsCreated: 0, notesSkipped: 0 };
    }

    const note = notes[0];
    const targetTitle = String(context.config.targetTitle || 'local title');
    await context.sdk.proposeChange({
      entityType: 'note',
      entityId: note.uuid,
      changeType: 'rename_note',
      before: { title: note.title, filename: note.filename },
      after: { newTitle: targetTitle, rewriteExactWikiLinks: true },
      preview: { oldTitle: note.title, proposedTitle: targetTitle, noteUuid: note.uuid },
      reason: 'Generated by local plugin test',
    });

    await context.sdk.log('info', 'Local plugin proposed rename', { noteUuid: note.uuid, targetTitle });
    return { notesScanned: 1, proposalsCreated: 1, notesSkipped: 0 };
  },
};
`;
}

function buildRunAllPluginSource(
  pluginId: string,
  title: string,
  opts?: { fail?: boolean; delayMs?: number },
): string {
  const delayMs = opts?.delayMs ?? 0;
  const fail = opts?.fail === true;
  return `export default {
  id: '${pluginId}',
  name: '${title}',
  description: 'Run-all automation test.',
  defaultEnabled: false,
  defaultSchedule: { kind: 'manual', time: null, day: null },
  defaultAutoApply: true,
  configSchema: [],
  async run(context) {
    await context.sdk.log('info', 'Starting ${pluginId}');
    ${delayMs > 0 ? `await new Promise((resolve) => setTimeout(resolve, ${delayMs}));` : ''}
    ${fail ? `throw new Error('Batch failure for ${pluginId}');` : ''}
    await context.sdk.log('info', 'Finished ${pluginId}');
    return { notesScanned: 0, proposalsCreated: 0, notesSkipped: 0 };
  },
};
`;
}

describe('Plugins', () => {
  let env: TestEnv;

  beforeEach(() => {
    env = createTestEnv();
    __setTestLlmResponder(null);
  });

  afterEach(() => {
    __setTestLlmResponder(null);
    env.cleanup();
  });

  it('lists built-in automation status', async () => {
    const token = await setupAndLogin(env.app);
    const res = await authReq(env.app, 'GET', '/plugins/status', token);
    expect(res.status).toBe(200);

    const data = await res.json() as {
      plugins: Array<{
        id: string;
        auto_apply: boolean;
        config_schema: Array<{ key: string; type?: string }>;
        config: Record<string, unknown>;
      }>;
      scheduler: { phase: string };
    };

    expect(data.scheduler.phase).toBe('idle');
    expect(data.plugins).toHaveLength(4);
    const autoTagger = data.plugins.find((plugin) => plugin.id === 'auto-tagger');
    const quickCapture = data.plugins.find((plugin) => plugin.id === 'quick-capture-to-list');
    const weeklyRelated = data.plugins.find((plugin) => plugin.id === 'weekly-related-notes');
    expect(autoTagger).toMatchObject({
      id: 'auto-tagger',
      auto_apply: true,
    });
    expect(autoTagger?.config_schema.map((field) => field.key)).toEqual([
      'tags',
      'confidenceThreshold',
      'maxContentChars',
      'staleMinutes',
      'maxNotesToScan',
    ]);
    expect(autoTagger?.config_schema[0]?.type).toBe('tag_list');
    expect(autoTagger?.config.maxNotesToScan).toBe(5);
    expect(quickCapture).toMatchObject({
      id: 'quick-capture-to-list',
      auto_apply: true,
      config_schema: [],
    });
    expect(weeklyRelated).toMatchObject({
      id: 'weekly-related-notes',
      auto_apply: true,
    });
    expect(weeklyRelated?.config_schema.map((field) => field.key)).toEqual([
      'lookbackDays',
      'maxLinks',
      'maxCandidateNotes',
      'targetFilenameRegex',
      'headingText',
      'includeReasons',
    ]);
    expect(weeklyRelated?.config.headingText).toBe('## Related Notes');
  });

  it('limits auto-tagger to the configured recent-note window and uses tagged examples', async () => {
    const token = await setupAndLogin(env.app);
    __setTestLlmResponder((input) => {
      // Example snippet (tag header stripped) should appear in prompt
      expect(input.userPrompt).toContain('FUTO Chat bug report from QA team');
      expect(input.userPrompt).toContain('Examples of #work:');
      expect(input.userPrompt).toContain('Note title:\nRecent');
      // Description should NOT appear when examples exist
      expect(input.userPrompt).not.toContain('no examples yet');
      return JSON.stringify({
        tags: [{ tag: 'work', confidence: 0.92 }],
      });
    });

    const configRes = await authReq(env.app, 'POST', '/plugins/auto-tagger/config', token, {
      auto_apply: false,
      schedule_kind: 'manual',
      config: {
        tags: [
          { name: 'work', description: 'work-related planning and roadmap notes' },
        ],
        confidenceThreshold: 0.7,
        maxNotesToScan: 1,
      },
    });
    expect(configRes.status).toBe(200);

    // Tagged example note — will be discovered as a few-shot example for #work
    seedNote(env, 'example-note', 'Bug Report.md', '#work\n\nFUTO Chat bug report from QA team about crash on startup and related issues.', Date.now() - (10 * 60 * 1000));
    // Untagged classification targets
    seedNote(env, 'recent-note', 'Recent.md', 'Sprint planning and roadmap discussion for the mobile client.', Date.now() - (20 * 60 * 1000));
    seedNote(env, 'older-note', 'Older.md', 'Quarterly planning and budget notes that should not be scanned.', Date.now() - (40 * 60 * 1000));

    const runRes = await authReq(env.app, 'POST', '/plugins/auto-tagger/run', token);
    expect(runRes.status).toBe(202);
    const { run_id } = await runRes.json() as { run_id: string };

    const detail = await waitForRunDetail(env.app, token, run_id) as {
      run: { status: string; summary: { notesScanned: number } | null };
      items: Array<{ entity_id: string; preview: { proposedTags?: string[] } }>;
    };

    expect(detail.run.status).toBe('awaiting_approval');
    expect(detail.run.summary?.notesScanned).toBe(1);
    expect(detail.items).toHaveLength(1);
    expect(detail.items[0].entity_id).toBe('recent-note');
    expect(detail.items[0].preview.proposedTags).toEqual(['work']);
  });

  it('round-trips structured auto-tagger tag definitions through plugin config', async () => {
    const token = await setupAndLogin(env.app);

    const configRes = await authReq(env.app, 'POST', '/plugins/auto-tagger/config', token, {
      auto_apply: false,
      schedule_kind: 'manual',
      config: {
        tags: [
          { name: 'work', description: 'roadmaps, projects, planning' },
          { name: 'research', description: 'experiments and investigation notes' },
        ],
      },
    });
    expect(configRes.status).toBe(200);

    const statusRes = await authReq(env.app, 'GET', '/plugins/status', token);
    expect(statusRes.status).toBe(200);
    const status = await statusRes.json() as {
      plugins: Array<{ id: string; config: { tags?: Array<{ name: string; description: string }> } }>;
    };

    const autoTagger = status.plugins.find((plugin) => plugin.id === 'auto-tagger');
    expect(autoTagger?.config.tags).toEqual([
      { name: 'work', description: 'roadmaps, projects, planning' },
      { name: 'research', description: 'experiments and investigation notes' },
    ]);
  });

  it('stops auto-tagger after a fatal llm failure instead of warning for every note', async () => {
    const token = await setupAndLogin(env.app);
    __setTestLlmResponder(() => {
      throw new Error('Built-in LLM is unavailable');
    });

    const configRes = await authReq(env.app, 'POST', '/plugins/auto-tagger/config', token, {
      auto_apply: false,
      schedule_kind: 'manual',
      config: {
        tags: [
          { name: 'work', description: 'work-related notes' },
        ],
        maxNotesToScan: 5,
      },
    });
    expect(configRes.status).toBe(200);

    for (let index = 0; index < 4; index += 1) {
      seedNote(
        env,
        `note-${index}`,
        `Note ${index}.md`,
        `Work planning note ${index} with enough content to trigger auto tagging.`,
        Date.now() - ((index + 1) * 20 * 60 * 1000),
      );
    }

    const runRes = await authReq(env.app, 'POST', '/plugins/auto-tagger/run', token);
    expect(runRes.status).toBe(202);
    const { run_id } = await runRes.json() as { run_id: string };

    const detail = await waitForRunDetail(env.app, token, run_id) as {
      run: { status: string; error_message: string | null };
      logs: Array<{ level: string; message: string }>;
    };

    expect(detail.run.status).toBe('failed');
    expect(detail.run.error_message).toContain('Auto Tagger stopped after repeated LLM failures');
    const noteFailureWarnings = detail.logs.filter((entry) => entry.message.startsWith('LLM call failed for note'));
    expect(noteFailureWarnings).toHaveLength(1);
  });

  it('skips Untitled and Untitled (N) notes in auto-tagger runs', async () => {
    const token = await setupAndLogin(env.app);
    let llmCalls = 0;
    __setTestLlmResponder(() => {
      llmCalls += 1;
      return JSON.stringify({
        tags: [{ tag: 'work', confidence: 0.92 }],
      });
    });

    const configRes = await authReq(env.app, 'POST', '/plugins/auto-tagger/config', token, {
      auto_apply: false,
      schedule_kind: 'manual',
      config: {
        tags: [
          { name: 'work', description: 'work-related notes' },
        ],
      },
    });
    expect(configRes.status).toBe(200);

    seedNote(env, 'untitled-note', 'Untitled.md', 'This note should not be tagged even though it has enough content.', Date.now() - (30 * 60 * 1000));
    seedNote(env, 'untitled-note-2', 'Untitled (2).md', 'This numbered untitled note should also be skipped by the tagger.', Date.now() - (35 * 60 * 1000));
    seedNote(env, 'regular-note', 'Regular.md', 'This planning note should still be tagged by the auto tagger.', Date.now() - (40 * 60 * 1000));

    const runRes = await authReq(env.app, 'POST', '/plugins/auto-tagger/run', token);
    expect(runRes.status).toBe(202);
    const { run_id } = await runRes.json() as { run_id: string };

    const detail = await waitForRunDetail(env.app, token, run_id) as {
      run: { status: string };
      items: Array<{ entity_id: string }>;
    };

    expect(detail.run.status).toBe('awaiting_approval');
    expect(detail.items).toHaveLength(1);
    expect(detail.items[0].entity_id).toBe('regular-note');
    expect(llmCalls).toBe(1);
  });

  it('cold start falls back to tag descriptions when no tagged notes exist', async () => {
    const token = await setupAndLogin(env.app);
    __setTestLlmResponder((input) => {
      expect(input.userPrompt).toContain('(no examples yet — work-related notes)');
      expect(input.userPrompt).toContain('(no examples yet — personal journals and life)');
      expect(input.userPrompt).toContain('Tags: work, personal');
      return JSON.stringify({ tags: ['work'] });
    });

    const configRes = await authReq(env.app, 'POST', '/plugins/auto-tagger/config', token, {
      auto_apply: false,
      schedule_kind: 'manual',
      config: {
        tags: [
          { name: 'work', description: 'work-related notes' },
          { name: 'personal', description: 'personal journals and life' },
        ],
      },
    });
    expect(configRes.status).toBe(200);

    seedNote(env, 'untagged-note', 'Planning.md', 'Sprint planning and roadmap discussion for the mobile client.', Date.now() - (20 * 60 * 1000));

    const runRes = await authReq(env.app, 'POST', '/plugins/auto-tagger/run', token);
    expect(runRes.status).toBe(202);
    const { run_id } = await runRes.json() as { run_id: string };

    const detail = await waitForRunDetail(env.app, token, run_id) as {
      run: { status: string };
      items: Array<{ entity_id: string }>;
    };

    expect(detail.run.status).toBe('awaiting_approval');
    expect(detail.items).toHaveLength(1);
    expect(detail.items[0].entity_id).toBe('untagged-note');
  });

  it('strips tag header from example snippets in auto-tagger prompt', async () => {
    const token = await setupAndLogin(env.app);
    __setTestLlmResponder((input) => {
      // The snippet should contain content AFTER the tag header, not the tag itself
      expect(input.userPrompt).toContain('Actual meeting notes about the product roadmap');
      expect(input.userPrompt).not.toMatch(/"Tagged Note": #work/);
      return JSON.stringify({ tags: ['work'] });
    });

    const configRes = await authReq(env.app, 'POST', '/plugins/auto-tagger/config', token, {
      auto_apply: false,
      schedule_kind: 'manual',
      config: {
        tags: [
          { name: 'work', description: 'work-related notes' },
        ],
      },
    });
    expect(configRes.status).toBe(200);

    // Example note with tag header that should be stripped
    seedNote(env, 'tagged-note', 'Tagged Note.md', '#work\n\nActual meeting notes about the product roadmap and deliverables.', Date.now() - (10 * 60 * 1000));
    // Classification target
    seedNote(env, 'target-note', 'Target.md', 'Budget review and financial planning for next quarter deliverables.', Date.now() - (20 * 60 * 1000));

    const runRes = await authReq(env.app, 'POST', '/plugins/auto-tagger/run', token);
    expect(runRes.status).toBe(202);
    const { run_id } = await runRes.json() as { run_id: string };

    const detail = await waitForRunDetail(env.app, token, run_id) as {
      run: { status: string };
      items: Array<{ entity_id: string }>;
    };

    expect(detail.run.status).toBe('awaiting_approval');
    expect(detail.items).toHaveLength(1);
    expect(detail.items[0].entity_id).toBe('target-note');
  });

  it('creates preview suggestions and applies approved quick-capture merge into the chosen list', async () => {
    const token = await setupAndLogin(env.app);
    __setTestLlmResponder((input) => {
      expect(input.disableThinking).not.toBe(true);
      expect(input.systemPrompt).toContain('Inbox is a fallback bucket only when no listed note makes sense.');
      return 'Packing';
    });

    const configRes = await authReq(env.app, 'POST', '/plugins/quick-capture-to-list/config', token, {
      auto_apply: false,
      schedule_kind: 'manual',
      config: {},
    });
    expect(configRes.status).toBe(200);

    const oldMtime = Date.now() - (10 * 60 * 1000);
    seedNote(env, 'note-1', 'Untitled.md', 'olive oil\nlemons', oldMtime);
    seedNote(env, 'note-2', 'Packing.md', 'Trip prep\n- socks\n- charger\n- passport\n\nLater\n- souvenirs', oldMtime);
    seedNote(env, 'note-3', 'Tasks.md', '- [ ] call mom\n- [x] pay rent\n- [ ] pack', oldMtime);

    const runRes = await authReq(env.app, 'POST', '/plugins/quick-capture-to-list/run', token);
    expect(runRes.status).toBe(202);
    const { run_id } = await runRes.json() as { run_id: string };

    const preview = await waitForRunDetail(env.app, token, run_id);
    expect(preview.run.status).toBe('awaiting_approval');
    expect(preview.items).toHaveLength(1);
    expect(preview.items[0].status).toBe('suggested');
    expect(preview.items[0].preview).toMatchObject({
      sourceTitle: 'Untitled',
      destinationTitle: 'Packing',
      destinationMode: 'existing',
      insertedListText: '- olive oil\n  - lemons',
      fallbackUsed: false,
    });

    const itemId = Number(preview.items[0].id);
    const approveRes = await authReq(env.app, 'POST', `/plugins/runs/${run_id}/items/${itemId}/approve`, token);
    expect(approveRes.status).toBe(200);

    const applyRes = await authReq(env.app, 'POST', `/plugins/runs/${run_id}/apply-approved`, token);
    expect(applyRes.status).toBe(200);

    const applied = await waitForRunDetail(env.app, token, run_id);
    expect(applied.run.status).toBe('succeeded');
    expect(applied.items[0].status).toBe('applied');

    expect(getNote(getDb(), 'note-1')).toBeNull();
    const packingContent = fs.readFileSync(path.join(env.notesDir, 'Packing.md'), 'utf8');
    expect(packingContent).toBe('Trip prep\n- socks\n- charger\n- passport\n- olive oil\n  - lemons\n\nLater\n- souvenirs');
    expect(fs.existsSync(path.join(env.notesDir, 'Untitled.md'))).toBe(false);
  });

  it('supports auto-apply runs and creates the fallback inbox when no list note matches', async () => {
    const token = await setupAndLogin(env.app);
    __setTestLlmResponder(() => 'Inbox');

    const configRes = await authReq(env.app, 'POST', '/plugins/quick-capture-to-list/config', token, {
      auto_apply: true,
      schedule_kind: 'manual',
      config: {},
    });
    expect(configRes.status).toBe(200);

    const oldMtime = Date.now() - (10 * 60 * 1000);
    seedNote(env, 'note-3', 'Untitled (2).md', 'call plumber', oldMtime);
    seedNote(env, 'note-4', 'Tasks.md', '- [ ] call mom\n- [ ] pay rent\n- [x] book flights', oldMtime);
    seedNote(env, 'note-4b', 'Gift ideas.md', '- dad socks\n- family router\n- birthday flowers', oldMtime);

    const runRes = await authReq(env.app, 'POST', '/plugins/quick-capture-to-list/run', token);
    expect(runRes.status).toBe(202);
    const { run_id } = await runRes.json() as { run_id: string };

    const detail = await waitForRunDetail(env.app, token, run_id);
    expect(detail.run.status).toBe('succeeded');
    expect(detail.items[0].status).toBe('applied');
    expect(detail.items[0].preview).toMatchObject({
      destinationTitle: 'Inbox',
      fallbackUsed: true,
    });

    const inbox = getNote(getDb(), detail.items[0].after.destinationUuid as string);
    expect(inbox?.filename).toBe('Inbox.md');
    const inboxContent = fs.readFileSync(path.join(env.notesDir, 'Inbox.md'), 'utf8');
    expect(inboxContent).toBe('- call plumber');
    expect(getNote(getDb(), 'note-3')).toBeNull();
  });

  it('prefers Gift ideas over Inbox for a recipient-style gift capture even when the model punts', async () => {
    const token = await setupAndLogin(env.app);
    let seenPrompt = '';
    __setTestLlmResponder((input) => {
      seenPrompt = input.userPrompt;
      expect(input.disableThinking).not.toBe(true);
      expect(input.systemPrompt).toContain('Recipient-plus-item captures usually belong in gift, wishlist, or ideas lists if one exists.');
      return 'Inbox';
    });

    const configRes = await authReq(env.app, 'POST', '/plugins/quick-capture-to-list/config', token, {
      auto_apply: false,
      schedule_kind: 'manual',
      config: {},
    });
    expect(configRes.status).toBe(200);

    const oldMtime = Date.now() - (10 * 60 * 1000);
    seedNote(env, 'gift-capture', 'Untitled.md', 'new computer for mom', oldMtime);
    seedNote(env, 'gift-inbox', 'Inbox.md', '- random thought\n- someday maybe\n- parking receipt', oldMtime);
    seedNote(env, 'gift-ideas', 'Gift ideas.md', [
      '#personal',
      '',
      "- **dad** Papadeux's gift card, japanese knife",
      '- 50OFF100',
      '- Darn tough socks',
      '- CarPlay',
      '- **Family** wifi router',
    ].join('\n'), oldMtime);
    seedNote(env, 'errands', 'Errands.md', '- call plumber\n- return package\n- buy batteries', oldMtime);

    const runRes = await authReq(env.app, 'POST', '/plugins/quick-capture-to-list/run', token);
    expect(runRes.status).toBe(202);
    const { run_id } = await runRes.json() as { run_id: string };

    const preview = await waitForRunDetail(env.app, token, run_id);
    expect(preview.run.status).toBe('awaiting_approval');
    expect(preview.items).toHaveLength(1);
    if (seenPrompt) {
      expect(seenPrompt).toContain('Existing list candidates:');
      expect(seenPrompt).toContain('- Gift ideas');
      expect(seenPrompt).not.toContain('- Inbox');
    }
    expect(preview.items[0].preview).toMatchObject({
      sourceTitle: 'Untitled',
      destinationTitle: 'Gift ideas',
      destinationMode: 'existing',
      insertedListText: '- new computer for mom',
      fallbackUsed: false,
    });
  });

  it('deletes every processed Untitled note after approved list and Inbox moves are applied', async () => {
    const token = await setupAndLogin(env.app);
    __setTestLlmResponder((input) => input.userPrompt.includes('Quick capture:\nbananas') ? 'Groceries' : 'null');

    const configRes = await authReq(env.app, 'POST', '/plugins/quick-capture-to-list/config', token, {
      auto_apply: false,
      schedule_kind: 'manual',
      config: {},
    });
    expect(configRes.status).toBe(200);

    const oldMtime = Date.now() - (10 * 60 * 1000);
    seedNote(env, 'note-move-1', 'Untitled.md', 'bananas', oldMtime);
    seedNote(env, 'note-move-2', 'Untitled (2).md', 'call plumber', oldMtime + 1);
    seedNote(env, 'note-move-3', 'Groceries.md', 'Groceries\n- apples\n- bread\n- cereal', oldMtime);

    const runRes = await authReq(env.app, 'POST', '/plugins/quick-capture-to-list/run', token);
    expect(runRes.status).toBe(202);
    const { run_id } = await runRes.json() as { run_id: string };

    const preview = await waitForRunDetail(env.app, token, run_id);
    expect(preview.run.status).toBe('awaiting_approval');
    expect(preview.items).toHaveLength(2);

    const approveRes = await authReq(env.app, 'POST', `/plugins/runs/${run_id}/approve-all`, token);
    expect(approveRes.status).toBe(200);

    const applyRes = await authReq(env.app, 'POST', `/plugins/runs/${run_id}/apply-approved`, token);
    expect(applyRes.status).toBe(200);

    const applied = await waitForRunDetail(env.app, token, run_id);
    expect(applied.run.status).toBe('succeeded');
    expect(applied.items.map((item) => item.status)).toEqual(['applied', 'applied']);

    const groceriesContent = fs.readFileSync(path.join(env.notesDir, 'Groceries.md'), 'utf8');
    expect(groceriesContent).toContain('- bananas');
    const inboxContent = fs.readFileSync(path.join(env.notesDir, 'Inbox.md'), 'utf8');
    expect(inboxContent).toBe('- call plumber');

    expect(getNote(getDb(), 'note-move-1')).toBeNull();
    expect(getNote(getDb(), 'note-move-2')).toBeNull();
    expect(fs.existsSync(path.join(env.notesDir, 'Untitled.md'))).toBe(false);
    expect(fs.existsSync(path.join(env.notesDir, 'Untitled (2).md'))).toBe(false);
  });

  it('broadcasts sync_available after an auto-applied quick-capture merge', async () => {
    const token = await setupAndLogin(env.app);
    __setTestLlmResponder(() => 'Errands');

    const configRes = await authReq(env.app, 'POST', '/plugins/quick-capture-to-list/config', token, {
      auto_apply: true,
      schedule_kind: 'manual',
      config: {},
    });
    expect(configRes.status).toBe(200);

    const ticket = await createSseTicket(env.app, token);
    const sseRes = await env.app.request(`/events?ticket=${ticket}&clientId=observer`);
    expect(sseRes.status).toBe(200);
    const sse = createSSEReader(sseRes);

    try {
      await sse.readUntil((buf) => buf.includes('event: connected'));

      const oldMtime = Date.now() - (10 * 60 * 1000);
      seedNote(env, 'note-5', 'Untitled.md', 'dish soap', oldMtime);
      seedNote(env, 'note-6', 'Errands.md', 'Errands\n1. stamps\n2. milk\n3. detergent', oldMtime);

      const runRes = await authReq(env.app, 'POST', '/plugins/quick-capture-to-list/run', token);
      expect(runRes.status).toBe(202);
      const { run_id } = await runRes.json() as { run_id: string };

      await sse.readUntil((buf) => buf.includes('event: sync_available'));
      const detail = await waitForRunDetail(env.app, token, run_id);
      expect(detail.run.status).toBe('succeeded');
      expect(sse.contents).toContain('event: sync_available');
      const errandsContent = fs.readFileSync(path.join(env.notesDir, 'Errands.md'), 'utf8');
      expect(errandsContent).toContain('4. dish soap');
    } finally {
      sse.cancel();
    }
  });

  it('bumps sync version after an auto-applied quick-capture merge', async () => {
    const token = await setupAndLogin(env.app);
    __setTestLlmResponder(() => 'Groceries');

    const beforeRes = await authReq(env.app, 'POST', '/sync/check', token, { version: 0 });
    expect(beforeRes.status).toBe(200);
    const before = await beforeRes.json() as { status: string; version: number };
    expect(before.status).toBe('up_to_date');
    expect(before.version).toBe(0);

    const configRes = await authReq(env.app, 'POST', '/plugins/quick-capture-to-list/config', token, {
      auto_apply: true,
      schedule_kind: 'manual',
      config: {},
    });
    expect(configRes.status).toBe(200);

    const oldMtime = Date.now() - (10 * 60 * 1000);
    seedNote(env, 'note-7', 'Untitled.md', 'bananas', oldMtime);
    seedNote(env, 'note-8', 'Groceries.md', 'Groceries\n- apples\n- bread\n- cereal', oldMtime);

    const runRes = await authReq(env.app, 'POST', '/plugins/quick-capture-to-list/run', token);
    expect(runRes.status).toBe(202);
    const { run_id } = await runRes.json() as { run_id: string };

    const detail = await waitForRunDetail(env.app, token, run_id);
    expect(detail.run.status).toBe('succeeded');

    const afterRes = await authReq(env.app, 'POST', '/sync/check', token, { version: 0 });
    expect(afterRes.status).toBe(200);
    const after = await afterRes.json() as { status: string; version: number };
    expect(after.status).toBe('changes_available');
    expect(after.version).toBeGreaterThan(0);
  });

  it('formats multiline captures as nested items and ignores task-list-only candidates', async () => {
    const token = await setupAndLogin(env.app);
    __setTestLlmResponder((input) => {
      expect(input.disableThinking).not.toBe(true);
      expect(input.userPrompt).toContain('Existing list candidates:');
      return 'Recipes';
    });

    const configRes = await authReq(env.app, 'POST', '/plugins/quick-capture-to-list/config', token, {
      auto_apply: false,
      schedule_kind: 'manual',
      config: {},
    });
    expect(configRes.status).toBe(200);

    const oldMtime = Date.now() - (10 * 60 * 1000);
    seedNote(env, 'note-9', 'Untitled.md', 'curry paste\ncoconut milk\nlime leaves', oldMtime);
    seedNote(env, 'note-10', 'Recipes.md', 'Shopping\n1. onions\n2. garlic\n3. ginger', oldMtime);
    seedNote(env, 'note-11', 'Checklist.md', '- [ ] mop\n- [ ] dust\n- [ ] vacuum', oldMtime);

    const runRes = await authReq(env.app, 'POST', '/plugins/quick-capture-to-list/run', token);
    expect(runRes.status).toBe(202);
    const { run_id } = await runRes.json() as { run_id: string };

    const preview = await waitForRunDetail(env.app, token, run_id);
    expect(preview.run.status).toBe('awaiting_approval');
    expect(preview.items[0].preview).toMatchObject({
      destinationTitle: 'Recipes',
      insertedListText: '4. curry paste\n  1. coconut milk\n  2. lime leaves',
      fallbackUsed: false,
    });
  });

  it('creates preview suggestions and applies a related-notes section to weekly notes', async () => {
    const token = await setupAndLogin(env.app);
    __setTestLlmResponder((input) => {
      expect(input.purpose).toBe('weekly-related-notes-selection');
      expect(input.disableThinking).toBe(true);
      return JSON.stringify({
        links: [
          { candidateId: 'c1', reason: 'Covers the same wow-demo framing.' },
          { candidateId: 'c2', reason: 'Earlier note on auto-backlinking and overnight jobs.' },
        ],
      });
    });

    const configRes = await authReq(env.app, 'POST', '/plugins/weekly-related-notes/config', token, {
      auto_apply: false,
      schedule_kind: 'manual',
      config: {},
    });
    expect(configRes.status).toBe(200);

    const weeklyMtime = new Date('2026-03-09T12:00:00Z').getTime();
    seedNote(env, 'weekly-1', 'This week (3-9-2026 to 3-14).md', [
      '- [ ] Fix bugs',
      '',
      'Still trying to think of what my "one more thing" moment is going to be.',
      '',
      'Semantic search is cool.',
      'Graph view could also be cool.',
      'What would be useful if an actual assistant did it?',
      'I think it\'s Smart Transforms.',
    ].join('\n'), weeklyMtime);
    seedNote(env, 'cand-1', 'Immediate Todos for FUTO Notes.md', [
      'the thing I want to actually demo are the cool advanced LLM/AI features.',
      'a cool demo: search for a document semantically.',
      'What if you could wake up to a message about your recent notes?',
    ].join('\n'), new Date('2026-02-26T12:00:00Z').getTime());
    seedNote(env, 'cand-2', 'FUTO Notes LLM Ideas.md', [
      '- Cron job support. What if you gave it a command to run nightly.',
      '- Auto backlink',
      '- graph view',
    ].join('\n'), new Date('2026-03-05T12:00:00Z').getTime());
    seedNote(env, 'cand-3', 'FUTO Notes Presentation Thoughts.md', 'Some notes about the presentation and demo this week.', new Date('2026-03-12T12:00:00Z').getTime());
    seedNote(env, 'cand-post-week', 'Next Sprint Planning.md', 'This note is after the weekly range and should not be included.', new Date('2026-03-16T12:00:00Z').getTime());

    const runRes = await authReq(env.app, 'POST', '/plugins/weekly-related-notes/run', token);
    expect(runRes.status).toBe(202);
    const { run_id } = await runRes.json() as { run_id: string };

    const preview = await waitForRunDetail(env.app, token, run_id);
    expect(preview.run.status).toBe('awaiting_approval');
    expect(preview.items).toHaveLength(1);
    expect(preview.items[0].preview).toMatchObject({
      title: 'This week (3-9-2026 to 3-14)',
      candidateCount: 3,
    });
    expect((preview.items[0].preview.selectedTitles as string[]).slice().sort()).toEqual([
      'FUTO Notes LLM Ideas',
      'Immediate Todos for FUTO Notes',
    ]);
    expect(String(preview.items[0].preview.renderedBlock)).toContain('[[Immediate Todos for FUTO Notes]]');
    expect(String(preview.items[0].preview.renderedBlock)).toContain('[[FUTO Notes LLM Ideas]]');
    expect(String(preview.items[0].preview.renderedBlock)).not.toContain('[[Next Sprint Planning]]');

    const itemId = Number(preview.items[0].id);
    const approveRes = await authReq(env.app, 'POST', `/plugins/runs/${run_id}/items/${itemId}/approve`, token);
    expect(approveRes.status).toBe(200);

    const applyRes = await authReq(env.app, 'POST', `/plugins/runs/${run_id}/apply-approved`, token);
    expect(applyRes.status).toBe(200);

    const applied = await waitForRunDetail(env.app, token, run_id);
    expect(applied.run.status).toBe('succeeded');
    expect(applied.items[0].status).toBe('applied');

    const weeklyContent = fs.readFileSync(path.join(env.notesDir, 'This week (3-9-2026 to 3-14).md'), 'utf8');
    expect(weeklyContent).toContain('## Related Notes');
    expect(weeklyContent).toContain('[[Immediate Todos for FUTO Notes]]');
    expect(weeklyContent).toContain('[[FUTO Notes LLM Ideas]]');
    expect(weeklyContent).toContain('Covers the same wow-demo framing.');
    expect(weeklyContent).toContain('Earlier note on auto-backlinking and overnight jobs.');
    expect(weeklyContent).not.toContain('[[Next Sprint Planning]]');
    expect(weeklyContent).not.toContain('stonefruit:weekly-related-notes:start');
  });

  it('does not duplicate the managed related-notes block across reruns', async () => {
    const token = await setupAndLogin(env.app);
    __setTestLlmResponder(() => JSON.stringify({
      links: [
        { candidateId: 'c1', reason: 'Matches the same demo thread.' },
      ],
    }));

    const weeklyMtime = new Date('2026-03-09T12:00:00Z').getTime();
    seedNote(env, 'weekly-2', 'This week (3-9-2026 to 3-14).md', 'Semantic search.\nSmart Transforms.', weeklyMtime);
    seedNote(env, 'cand-4', 'Immediate Todos for FUTO Notes.md', 'semantic search\nwow demo', new Date('2026-03-01T12:00:00Z').getTime());

    const configRes = await authReq(env.app, 'POST', '/plugins/weekly-related-notes/config', token, {
      auto_apply: true,
      schedule_kind: 'manual',
      config: {
        maxLinks: 1,
      },
    });
    expect(configRes.status).toBe(200);

    const firstRunRes = await authReq(env.app, 'POST', '/plugins/weekly-related-notes/run', token);
    expect(firstRunRes.status).toBe(202);
    const firstRun = await firstRunRes.json() as { run_id: string };
    const firstDetail = await waitForRunDetail(env.app, token, firstRun.run_id);
    expect(firstDetail.run.status).toBe('succeeded');

    const secondRunRes = await authReq(env.app, 'POST', '/plugins/weekly-related-notes/run', token);
    expect(secondRunRes.status).toBe(202);
    const secondRun = await secondRunRes.json() as { run_id: string };
    const secondDetail = await waitForRunDetail(env.app, token, secondRun.run_id);
    expect(secondDetail.run.status).toBe('succeeded');
    expect(secondDetail.items).toHaveLength(0);

    const weeklyContent = fs.readFileSync(path.join(env.notesDir, 'This week (3-9-2026 to 3-14).md'), 'utf8');
    expect(weeklyContent.match(/^## Related Notes$/gm)).toHaveLength(1);
  });

  it('creates, edits, runs, and deletes a local plugin while keeping run history', async () => {
    const token = await setupAndLogin(env.app);
    seedNote(env, 'local-note-1', 'Untitled.md', 'This note should be renamed by a local plugin.', Date.now() - 60_000);

    const createRes = await authReq(env.app, 'POST', '/plugins/local', token, {
      plugin_id: 'local-renamer',
      source: buildLocalPluginSource('local-renamer', 'Local Renamer'),
    });
    expect(createRes.status).toBe(201);

    const statusRes = await authReq(env.app, 'GET', '/plugins/status', token);
    expect(statusRes.status).toBe(200);
    const status = await statusRes.json() as {
      plugins: Array<{ id: string; source_kind: string; source_label: string; can_edit: boolean }>;
    };
    const localPlugin = status.plugins.find((plugin) => plugin.id === 'local-renamer');
    expect(localPlugin).toMatchObject({
      id: 'local-renamer',
      source_kind: 'local',
      source_label: 'Local',
      can_edit: true,
    });

    const sourceRes = await authReq(env.app, 'GET', '/plugins/local/local-renamer/source', token);
    expect(sourceRes.status).toBe(200);
    const sourceData = await sourceRes.json() as { source: string };
    expect(sourceData.source).toContain("name: 'Local Renamer'");

    const configRes = await authReq(env.app, 'POST', '/plugins/local-renamer/config', token, {
      auto_apply: false,
      schedule_kind: 'manual',
      config: {
        targetTitle: 'local title',
      },
    });
    expect(configRes.status).toBe(200);

    const runRes = await authReq(env.app, 'POST', '/plugins/local-renamer/run', token);
    expect(runRes.status).toBe(202);
    const { run_id } = await runRes.json() as { run_id: string };

    const preview = await waitForRunDetail(env.app, token, run_id);
    expect(preview.run.status).toBe('awaiting_approval');
    expect(preview.items).toHaveLength(1);
    expect(preview.items[0].preview).toMatchObject({
      oldTitle: 'Untitled',
      proposedTitle: 'local title',
    });

    const updateRes = await authReq(env.app, 'PUT', '/plugins/local/local-renamer/source', token, {
      source: buildLocalPluginSource('local-renamer', 'Local Renamer v2', 'Updated local automation.'),
    });
    expect(updateRes.status).toBe(200);

    const updatedStatusRes = await authReq(env.app, 'GET', '/plugins/status', token);
    expect(updatedStatusRes.status).toBe(200);
    const updatedStatus = await updatedStatusRes.json() as {
      plugins: Array<{ id: string; name: string; description: string }>;
    };
    expect(updatedStatus.plugins.find((plugin) => plugin.id === 'local-renamer')).toMatchObject({
      id: 'local-renamer',
      name: 'Local Renamer v2',
      description: 'Updated local automation.',
    });

    const deleteRes = await authReq(env.app, 'DELETE', '/plugins/local/local-renamer', token);
    expect(deleteRes.status).toBe(200);

    const statusAfterDeleteRes = await authReq(env.app, 'GET', '/plugins/status', token);
    expect(statusAfterDeleteRes.status).toBe(200);
    const statusAfterDelete = await statusAfterDeleteRes.json() as {
      plugins: Array<{ id: string }>;
    };
    expect(statusAfterDelete.plugins.find((plugin) => plugin.id === 'local-renamer')).toBeUndefined();

    const runDetailAfterDeleteRes = await authReq(env.app, 'GET', `/plugins/runs/${run_id}`, token);
    expect(runDetailAfterDeleteRes.status).toBe(200);
    const runDetailAfterDelete = await runDetailAfterDeleteRes.json() as { run: { plugin_id: string } };
    expect(runDetailAfterDelete.run.plugin_id).toBe('local-renamer');
  });

  it('runs enabled automations sequentially in a run-all batch and keeps going after failures', async () => {
    const token = await setupAndLogin(env.app);

    const createAlpha = await authReq(env.app, 'POST', '/plugins/local', token, {
      plugin_id: 'batch-alpha',
      source: buildRunAllPluginSource('batch-alpha', 'Batch Alpha', { delayMs: 20 }),
    });
    expect(createAlpha.status).toBe(201);

    const createBeta = await authReq(env.app, 'POST', '/plugins/local', token, {
      plugin_id: 'batch-beta',
      source: buildRunAllPluginSource('batch-beta', 'Batch Beta', { fail: true, delayMs: 20 }),
    });
    expect(createBeta.status).toBe(201);

    const createGamma = await authReq(env.app, 'POST', '/plugins/local', token, {
      plugin_id: 'batch-gamma',
      source: buildRunAllPluginSource('batch-gamma', 'Batch Gamma', { delayMs: 20 }),
    });
    expect(createGamma.status).toBe(201);

    const createDisabled = await authReq(env.app, 'POST', '/plugins/local', token, {
      plugin_id: 'batch-disabled',
      source: buildRunAllPluginSource('batch-disabled', 'Batch Disabled'),
    });
    expect(createDisabled.status).toBe(201);

    // Disable builtins so the batch only contains the local test plugins
    expect((await authReq(env.app, 'POST', '/plugins/auto-tagger/disable', token)).status).toBe(200);
    expect((await authReq(env.app, 'POST', '/plugins/quick-capture-to-list/disable', token)).status).toBe(200);
    expect((await authReq(env.app, 'POST', '/plugins/weekly-related-notes/disable', token)).status).toBe(200);

    expect((await authReq(env.app, 'POST', '/plugins/batch-alpha/enable', token)).status).toBe(200);
    expect((await authReq(env.app, 'POST', '/plugins/batch-beta/enable', token)).status).toBe(200);
    expect((await authReq(env.app, 'POST', '/plugins/batch-gamma/enable', token)).status).toBe(200);

    const runAllRes = await authReq(env.app, 'POST', '/plugins/run-all', token);
    expect(runAllRes.status).toBe(202);
    const runAllData = await runAllRes.json() as {
      batch_id: string;
      queued_count: number;
      batch: { items: Array<{ plugin_id: string; status: string }> };
    };

    expect(runAllData.queued_count).toBe(3);
    expect(runAllData.batch.items.map((item) => item.plugin_id)).toEqual([
      'batch-alpha',
      'batch-beta',
      'batch-gamma',
    ]);
    expect(runAllData.batch.items.every((item) => item.plugin_id !== 'batch-disabled')).toBe(true);

    const completedBatch = await waitForRunAllBatch(env.app, token, runAllData.batch_id);
    expect(completedBatch.items).toMatchObject([
      { plugin_id: 'batch-alpha', status: 'succeeded', error_message: null },
      { plugin_id: 'batch-beta', status: 'failed', error_message: 'Batch failure for batch-beta' },
      { plugin_id: 'batch-gamma', status: 'succeeded', error_message: null },
    ]);

    const runRows = getDb().prepare(`
      SELECT plugin_id, status, started_at, finished_at
      FROM plugin_runs
      WHERE plugin_id IN ('batch-alpha', 'batch-beta', 'batch-gamma')
      ORDER BY started_at ASC
    `).all() as Array<{ plugin_id: string; status: string; started_at: number; finished_at: number }>;

    expect(runRows.map((row) => row.plugin_id)).toEqual(['batch-alpha', 'batch-beta', 'batch-gamma']);
    expect(runRows.map((row) => row.status)).toEqual(['succeeded', 'failed', 'succeeded']);
    expect(runRows[1].started_at).toBeGreaterThanOrEqual(runRows[0].finished_at);
    expect(runRows[2].started_at).toBeGreaterThanOrEqual(runRows[1].finished_at);
  });
});
