// Conformance test (TypeScript side).
//
// Reads the language-neutral golden fixtures in tests/conformance/*.json and
// asserts the canonical TypeScript rules (filename/tags here in
// @futo-notes/editor, image in @futo-notes/shared) reproduce every expected
// output. The same fixtures are read by the Rust model crate
// (crates/futo-notes-model/tests/conformance.rs), so a rule that drifts in
// either language fails here or there.
//
// Fixtures are generated by tests/conformance/generate.mjs from this very
// implementation, so this test is also a guard against editing a rule
// without regenerating: change filename.ts but not the fixture and this
// test goes red.

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import {
  sanitizeTitle,
  validateTitle,
  isValidTitle,
  isWindowsReservedName,
  validateFolderName,
  isValidFolderName,
  hasCaseInsensitiveSiblingCollision,
  validateFolderPath,
  isValidFolderPath,
  pathDepth,
} from './filename';
import {
  TAG_REGEX,
  isValidTagName,
  normalizeTagName,
  extractTags,
  extractHeaderTagBlock,
} from './tags';
import { makePreview } from './preview';
import { isImageFilename, IMAGE_EXTENSIONS } from '@futo-notes/shared';

const CONFORMANCE_DIR = join(dirname(fileURLToPath(import.meta.url)), '../../../tests/conformance');

const kinds = (issues: { kind: string }[]) => issues.map((i) => i.kind);

function tagRegexMatches(content: string): string[] {
  const re = new RegExp(TAG_REGEX.source, TAG_REGEX.flags);
  const out: string[] = [];
  let m: RegExpExecArray | null;
  while ((m = re.exec(content)) !== null) out.push(m[1]);
  return out;
}

// Dispatch a language-neutral op name → the actual TS computation.
const OPS: Record<string, (input: unknown) => unknown> = {
  sanitizeTitle: (i) => sanitizeTitle(i as string),
  validateTitle: (i) => kinds(validateTitle(i as string)),
  isValidTitle: (i) => isValidTitle(i as string),
  isWindowsReservedName: (i) => isWindowsReservedName(i as string),
  validateFolderName: (i) => kinds(validateFolderName(i as string)),
  isValidFolderName: (i) => isValidFolderName(i as string),
  hasCaseInsensitiveSiblingCollision: (i) => {
    const { name, siblings } = i as { name: string; siblings: string[] };
    return hasCaseInsensitiveSiblingCollision(name, siblings);
  },
  validateFolderPath: (i) => kinds(validateFolderPath(i as string)),
  isValidFolderPath: (i) => isValidFolderPath(i as string),
  pathDepth: (i) => pathDepth(i as string),
  tagRegexMatches: (i) => tagRegexMatches(i as string),
  isValidTagName: (i) => isValidTagName(i as string),
  normalizeTagName: (i) => normalizeTagName(i as string),
  extractTags: (i) => extractTags(i as string),
  extractHeaderTagBlock: (i) => {
    const content = i as string;
    const { tags, endOffset } = extractHeaderTagBlock(content);
    return { tags, endOffset, remainder: content.slice(endOffset) };
  },
  isImageFilename: (i) => isImageFilename(i as string),
  imageExtensions: () => [...IMAGE_EXTENSIONS],
  makePreview: (i) => makePreview(i as string),
};

interface Case {
  input: unknown;
  expected: unknown;
}
interface Group {
  op: string;
  fn: string;
  cases: Case[];
}
interface Fixture {
  description: string;
  groups: Group[];
}

function loadFixture(name: string): Fixture {
  return JSON.parse(readFileSync(join(CONFORMANCE_DIR, `${name}.json`), 'utf8')) as Fixture;
}

for (const fixtureName of ['filename', 'tags', 'image']) {
  const fixture = loadFixture(fixtureName);
  describe(`conformance: ${fixtureName} (${fixture.description})`, () => {
    for (const group of fixture.groups) {
      const op = OPS[group.op];
      it(`has a dispatcher for op "${group.op}"`, () => {
        expect(op, `missing OPS entry for ${group.op}`).toBeTypeOf('function');
      });
      if (!op) continue;
      for (const [i, c] of group.cases.entries()) {
        it(`${group.op}[${i}] ${JSON.stringify(c.input)?.slice(0, 60)}`, () => {
          expect(op(c.input)).toEqual(c.expected);
        });
      }
    }
  });
}
