use crate::cli::UpdateArgs;
use crate::{config, docker, server_api, settings};
use anyhow::{bail, Context, Result};
use crossterm::execute;
use crossterm::style::{Attribute, Color, Print, ResetColor, SetAttribute, SetForegroundColor};
use std::io::{stdout, Write};
use std::time::Instant;

const PRIMARY: Color = Color::Rgb {
    r: 176,
    g: 125,
    b: 59,
};
const SUCCESS: Color = Color::Rgb {
    r: 61,
    g: 122,
    b: 63,
};
const MUTED: Color = Color::Rgb {
    r: 120,
    g: 113,
    b: 108,
};

pub fn run(args: UpdateArgs) -> Result<()> {
    let started = Instant::now();
    let work_dir = settings::resolve_work_dir(args.compose_dir.as_deref())?;

    if !work_dir.join("docker-compose.yml").exists() {
        bail!(
            "No docker-compose.yml found in {}. Run 'stonefruit setup' first.",
            work_dir.display()
        );
    }

    // Migrate compose file if needed (fix volume mount path from old releases)
    migrate_compose_volume(&work_dir)?;
    let config = config::load_or_infer(&work_dir)?;
    config::write_managed_files(&work_dir, &config)?;

    // Check Docker
    step("Checking Docker")?;
    let version = docker::check_docker()?;
    done(&format!("Docker {}", version))?;

    // Snapshot current image
    let old_image = docker::get_container_image_id("stonefruit")?;

    // Pull
    step("Pulling latest image")?;
    docker::compose_pull(&work_dir)?;
    done("done")?;

    // Recreate
    step("Restarting container")?;
    docker::compose_up_recreate(&work_dir)?;
    done("done")?;

    // Health check
    let base_url = settings::base_url(config.port);
    step("Waiting for server")?;
    server_api::wait_for_healthy(&base_url, config.startup_timeout())?;
    done("healthy")?;

    // Compare images
    let new_image = docker::get_container_image_id("stonefruit")?;
    println!();
    print_result(&old_image, &new_image)?;

    // Elapsed
    let elapsed = started.elapsed().as_secs();
    print_elapsed(elapsed)?;

    Ok(())
}

fn step(label: &str) -> Result<()> {
    execute!(
        stdout(),
        SetForegroundColor(MUTED),
        Print(format!("  {}... ", label)),
        ResetColor,
    )?;
    stdout().flush()?;
    Ok(())
}

fn done(text: &str) -> Result<()> {
    execute!(stdout(), Print(format!("{}\n", text)))?;
    Ok(())
}

fn short_id(full: &str) -> &str {
    let s = full.strip_prefix("sha256:").unwrap_or(full);
    let end = s.len().min(12);
    &s[..end]
}

fn print_result(old: &Option<String>, new: &Option<String>) -> Result<()> {
    match (old, new) {
        (Some(old_id), Some(new_id)) if old_id != new_id => {
            execute!(
                stdout(),
                Print("  "),
                SetForegroundColor(SUCCESS),
                SetAttribute(Attribute::Bold),
                Print("Updated to a new version."),
                SetAttribute(Attribute::Reset),
                ResetColor,
                Print("\n"),
                Print("  "),
                SetForegroundColor(MUTED),
                Print(format!(
                    "Image: {} \u{2192} {}",
                    short_id(old_id),
                    short_id(new_id)
                )),
                ResetColor,
                Print("\n"),
            )?;
        }
        (_, Some(new_id)) if old.is_none() => {
            execute!(
                stdout(),
                Print("  "),
                SetForegroundColor(SUCCESS),
                SetAttribute(Attribute::Bold),
                Print("Container created."),
                SetAttribute(Attribute::Reset),
                ResetColor,
                Print("\n"),
                Print("  "),
                SetForegroundColor(MUTED),
                Print(format!("Image: {}", short_id(new_id))),
                ResetColor,
                Print("\n"),
            )?;
        }
        (Some(old_id), Some(_)) => {
            execute!(
                stdout(),
                Print("  "),
                SetForegroundColor(PRIMARY),
                Print("Already up to date."),
                ResetColor,
                Print("\n"),
                Print("  "),
                SetForegroundColor(MUTED),
                Print(format!("Image: {}", short_id(old_id))),
                ResetColor,
                Print("\n"),
            )?;
        }
        _ => {
            println!("  Server is running.");
        }
    }
    Ok(())
}

/// Fix the volume mount path in compose files generated by older CLI versions.
/// Old path: `…:/app/apps/server/data` → new: `…:/app/data`.
fn migrate_compose_volume(work_dir: &std::path::Path) -> Result<()> {
    let compose_path = work_dir.join("docker-compose.yml");
    let content = std::fs::read_to_string(&compose_path)
        .with_context(|| format!("failed to read {}", compose_path.display()))?;

    if !content.contains(":/app/apps/server/data") {
        return Ok(());
    }

    step("Migrating compose volume path")?;
    let updated = content.replace(":/app/apps/server/data", ":/app/data");
    std::fs::write(&compose_path, updated)
        .with_context(|| format!("failed to write {}", compose_path.display()))?;
    done("done")?;

    Ok(())
}

fn print_elapsed(seconds: u64) -> Result<()> {
    execute!(
        stdout(),
        Print("\n  "),
        SetForegroundColor(MUTED),
        Print(format!("Done in {}s.", seconds)),
        ResetColor,
        Print("\n"),
    )?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn short_id_strips_sha256_prefix() {
        assert_eq!(short_id("sha256:abc123def456789"), "abc123def456");
    }

    #[test]
    fn short_id_handles_no_prefix() {
        assert_eq!(short_id("abc123def456789"), "abc123def456");
    }

    #[test]
    fn short_id_handles_short_input() {
        assert_eq!(short_id("sha256:abc"), "abc");
    }

    #[test]
    fn migrate_fixes_old_volume_path() {
        let dir = std::env::temp_dir().join("stonefruit-migrate-test");
        let _ = std::fs::create_dir_all(&dir);
        let compose = dir.join("docker-compose.yml");
        std::fs::write(
            &compose,
            "volumes:\n      - \"./data:/app/apps/server/data\"\n",
        )
        .unwrap();
        migrate_compose_volume(&dir).unwrap();
        let result = std::fs::read_to_string(&compose).unwrap();
        assert!(result.contains(":/app/data"));
        assert!(!result.contains(":/app/apps/server/data"));
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn migrate_skips_already_correct() {
        let dir = std::env::temp_dir().join("stonefruit-migrate-noop-test");
        let _ = std::fs::create_dir_all(&dir);
        let compose = dir.join("docker-compose.yml");
        let content = "volumes:\n      - \"./data:/app/data\"\n";
        std::fs::write(&compose, content).unwrap();
        migrate_compose_volume(&dir).unwrap();
        let result = std::fs::read_to_string(&compose).unwrap();
        assert_eq!(result, content);
        let _ = std::fs::remove_dir_all(&dir);
    }
}
