//! Rust side of the cross-language conformance harness.
//!
//! Reads the SAME golden fixtures the TypeScript reference is pinned to
//! (`tests/conformance/{filename,tags,image,preview}.json`, generated by
//! `tests/conformance/generate.mjs`) and asserts `futo-notes-model` reproduces
//! every expected output bit-for-bit. If a rule drifts in Rust this test goes
//! red; if it drifts in TS, the Vitest conformance test
//! (`packages/editor/src/conformance.test.ts`) goes red. Rule drift therefore
//! cannot land silently in either language.

use std::path::PathBuf;

use futo_notes_model as model;
use serde_json::Value;

fn conformance_dir() -> PathBuf {
    // crates/futo-notes-model/tests/ -> repo root -> tests/conformance
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../tests/conformance")
        .canonicalize()
        .expect("tests/conformance must exist")
}

fn load(name: &str) -> Value {
    let path = conformance_dir().join(format!("{name}.json"));
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    serde_json::from_str(&text).expect("fixture is valid JSON")
}

/// Issue kinds as snake_case strings, matching the TS `kind` union.
fn kinds(issues: &[model::FilenameIssue]) -> Vec<String> {
    issues.iter().map(|i| i.kind.as_str().to_string()).collect()
}

/// A JSON string-array field of an input object → `Vec<String>`.
fn string_vec(input: &Value, key: &str) -> Vec<String> {
    input
        .get(key)
        .and_then(|v| v.as_array())
        .map(|a| a.iter().filter_map(|v| v.as_str().map(String::from)).collect())
        .unwrap_or_default()
}

/// Dispatch a language-neutral op + input → a JSON value comparable to the
/// fixture's `expected`.
fn run_op(op: &str, input: &Value) -> Value {
    let s = || input.as_str().unwrap_or_default().to_string();
    match op {
        "sanitizeTitle" => Value::from(model::sanitize_title(&s())),
        "validateTitle" => Value::from(kinds(&model::validate_title(&s()))),
        "isValidTitle" => Value::from(model::is_valid_title(&s())),
        "isWindowsReservedName" => Value::from(model::is_windows_reserved_name(&s())),
        "validateFolderName" => Value::from(kinds(&model::validate_folder_name(&s()))),
        "isValidFolderName" => Value::from(model::is_valid_folder_name(&s())),
        "hasCaseInsensitiveSiblingCollision" => {
            let name = input.get("name").and_then(|v| v.as_str()).unwrap_or_default();
            let siblings: Vec<String> = input
                .get("siblings")
                .and_then(|v| v.as_array())
                .map(|a| a.iter().filter_map(|v| v.as_str().map(String::from)).collect())
                .unwrap_or_default();
            Value::from(model::has_case_insensitive_sibling_collision(name, &siblings))
        }
        "validateFolderPath" => Value::from(kinds(&model::validate_folder_path(&s()))),
        "isValidFolderPath" => Value::from(model::is_valid_folder_path(&s())),
        "pathDepth" => Value::from(model::path_depth(&s())),
        "tagRegexMatches" => Value::from(model::tags::tag_regex_matches(&s())),
        "isValidTagName" => Value::from(model::is_valid_tag_name(&s())),
        "normalizeTagName" => Value::from(model::normalize_tag_name(&s())),
        "extractTags" => Value::from(model::extract_tags(&s())),
        "extractHeaderTagBlock" => {
            let content = s();
            let block = model::extract_header_tag_block(&content);
            serde_json::json!({
                "tags": block.tags,
                "endOffset": block.end_offset,
                "remainder": &content[block.end_offset..],
            })
        }
        "makePreview" => Value::from(model::make_preview(&s())),
        "resolveWikilink" => {
            let target = input.get("target").and_then(|v| v.as_str()).unwrap_or_default();
            let all_ids = string_vec(input, "allIds");
            match model::resolve_wikilink(target, &all_ids) {
                Some(id) => Value::from(id),
                None => Value::Null,
            }
        }
        "shortestUniqueSuffix" => {
            let target_id = input.get("targetId").and_then(|v| v.as_str()).unwrap_or_default();
            let all_ids = string_vec(input, "allIds");
            Value::from(model::shortest_unique_suffix(target_id, &all_ids))
        }
        "rewriteWikilinks" => {
            let text = input.get("text").and_then(|v| v.as_str()).unwrap_or_default();
            let old_id = input.get("oldId").and_then(|v| v.as_str()).unwrap_or_default();
            let new_id = input.get("newId").and_then(|v| v.as_str()).unwrap_or_default();
            let all_ids = string_vec(input, "allIds");
            let (out, rewrites) = model::rewrite_wikilinks(text, old_id, new_id, &all_ids);
            serde_json::json!({ "text": out, "rewrites": rewrites })
        }
        "isImageFilename" => Value::from(model::is_image_filename(&s())),
        "imageExtensions" => Value::from(
            model::IMAGE_EXTENSIONS
                .iter()
                .map(|e| e.to_string())
                .collect::<Vec<_>>(),
        ),
        other => panic!("no Rust dispatcher for conformance op {other:?}"),
    }
}

/// Compare two JSON values, normalizing integer vs float (serde emits usize as
/// u64, fixtures may carry plain numbers) so `endOffset: 6` matches `6`.
fn json_eq(a: &Value, b: &Value) -> bool {
    match (a, b) {
        (Value::Number(x), Value::Number(y)) => {
            x.as_f64().zip(y.as_f64()).map(|(p, q)| p == q).unwrap_or(false)
        }
        (Value::Array(x), Value::Array(y)) => {
            x.len() == y.len() && x.iter().zip(y).all(|(p, q)| json_eq(p, q))
        }
        (Value::Object(x), Value::Object(y)) => {
            x.len() == y.len()
                && x.iter()
                    .all(|(k, v)| y.get(k).map(|w| json_eq(v, w)).unwrap_or(false))
        }
        _ => a == b,
    }
}

fn check_fixture(name: &str) {
    let fixture = load(name);
    let groups = fixture["groups"].as_array().expect("groups array");
    let mut failures = Vec::new();
    let mut total = 0usize;
    for group in groups {
        let op = group["op"].as_str().expect("op string");
        for (i, case) in group["cases"].as_array().expect("cases").iter().enumerate() {
            total += 1;
            let input = &case["input"];
            let expected = &case["expected"];
            let actual = run_op(op, input);
            if !json_eq(&actual, expected) {
                failures.push(format!(
                    "  {op}[{i}] input={input}\n     expected={expected}\n     actual  ={actual}"
                ));
            }
        }
    }
    assert!(
        failures.is_empty(),
        "{} conformance failures in {name}.json (of {total}):\n{}",
        failures.len(),
        failures.join("\n")
    );
}

#[test]
fn filename_conformance() {
    check_fixture("filename");
}

#[test]
fn tags_conformance() {
    check_fixture("tags");
}

#[test]
fn image_conformance() {
    check_fixture("image");
}

#[test]
fn preview_conformance() {
    check_fixture("preview");
}

#[test]
fn wikilinks_conformance() {
    check_fixture("wikilinks");
}

/// Cross-language constants gate (architecture-hardening.md PKT-7 gate 3).
/// `tests/conformance/constants.json` also asserted from
/// `apps/tauri/src-tauri/src/filesystem_watcher.rs` (SUPPRESSION_WINDOW_MS —
/// a different crate, not reachable from here) and
/// `src/lib/constantsConformance.test.ts` (TS side of all fields).
#[test]
fn constants_conformance() {
    let fixture = load("constants");
    let expected_exts: Vec<String> = fixture["imageExtensions"]
        .as_array()
        .expect("imageExtensions array")
        .iter()
        .map(|v| v.as_str().expect("extension is a string").to_string())
        .collect();
    let actual_exts: Vec<String> =
        model::IMAGE_EXTENSIONS.iter().map(|e| e.to_string()).collect();
    assert_eq!(
        actual_exts, expected_exts,
        "futo_notes_model::IMAGE_EXTENSIONS drifted from tests/conformance/constants.json"
    );

    let expected_max_title_length = fixture["maxTitleLength"]
        .as_u64()
        .expect("maxTitleLength") as usize;
    assert_eq!(
        model::MAX_TITLE_LENGTH, expected_max_title_length,
        "futo_notes_model::MAX_TITLE_LENGTH drifted from tests/conformance/constants.json"
    );
}
